### ISSUE TITLE
Allow to compile to json object instead of to directory

### ISSUE THREAD

**Issue by rogierschouten** [artifacthealth/tsreflect-compiler#1]
For integration with the gulp build system, it would be nice if the commonjs compiler module could output a json object instead of a json file. I'm currently working on a gulp plugin for tsreflect-compiler. As it is, it will be a bit broken because gulp doesn't expect plugins to write files themselves (it's stream-oriented).

**Comment by meirgottlieb** [comment]
I just added an option to pass a CompilerHost to the compiler. I don't expose the full CompilerHost from the TypeScript compiler, so it should be easier to implement. Take a look at the function createCompilerHost on line 222 of compiler.ts and the test in compiler.tests.ts for examples of implementing the host.

**Comment by rogierschouten** [comment]
That looks like it will help. Thank you!

**Comment by rogierschouten** [comment]
Works, thank you!  gulp-tsreflect now pipes the JSON files into the gulp stream. Maybe you could mention the plugin on your README.md next to the grunt plugin.

**Comment by meirgottlieb** [comment]
Glad it worked. I’ll add it to the tsreflect-compiler README.
