### ISSUE TITLE
Please support TypeScript 1.5

### ISSUE THREAD

**Issue by rogierschouten** [artifacthealth/tsreflect-compiler#4]
Sorry I posted this on tsreflect, but I guess I should post it on tsreflect-compiler instead. So here goes:
We moved to TypeScript 1.5, and we noticed ts-reflect no longer working on some of the newer source code. Are there any plans to move to the new compiler with ts-reflect?

**Comment by meirgottlieb** [comment]
I do plan on supporting 1.5. However, the way I've been handling new versions of TypeScript is by rewriting the emitter for each release. With 1.5 the the changes to the emitter were so substantial that I don't feel I can continue with this approach. I'm going to try to re-write tsreflect-compiler to use the language services instead. I'm hoping this approach will be more stable. However, I'm not going to have time to do this until September.

**Comment by rogierschouten** [comment]
That's all I can ask for :)   Thanks.

**Comment by jcristovao** [comment]
Hi,
@meirgottlieb , is there in chance that you will pick up this in the near future?
Thanks

**Comment by meirgottlieb** [comment]
Hey @jcristovao,

Unfortunately not. The approach of modifying the TypeScript emitter is too difficult to maintain, considering how quickly the TypeScript language/compiler is evolving. If in the future the TypeScript compiler supports an extensible emitter, I'll pick this project up again. Until that time, I'm dropping it in my projects in favor of the current experimental decorator support in TypeScript.

Meir
